export const SET_ERROR = 'SET_ERROR'
export const SET_LOADING = 'SET_LOADING'
export const SET_SIGNIN = 'AUTHENTICATE'
export const SET_SIGNUP = 'SET_SIGNUP'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const SET_STATUS = 'CONTACT_STATUS'
export const SET_LOCALE = 'SET_LOCALE'
export const SET_BURGER = 'SET_BURGER'
